### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by hbakhtiyor** [gen2brain/url2img#7]
```
 ~/D/url2img-1.2-64bit ./url2img 
127.0.0.1 - - [04/May/2017:21:19:56 +0500] "GET /?url=producthunt.com HTTP/1.1 200 153563" 12.020650 
127.0.0.1 - - [04/May/2017:21:20:08 +0500] "GET /?url=producthunt.com&zoom=0.5 HTTP/1.1 200 104926" 12.334749 
127.0.0.1 - - [04/May/2017:21:20:10 +0500] "GET /?url=producthunt.com&zoom=0.5 HTTP/1.1 200 106271" 7.738079 
127.0.0.1 - - [04/May/2017:21:20:14 +0500] "GET /?url=producthunt.com&zoom=0.5 HTTP/1.1 200 95477" 5.529129 
127.0.0.1 - - [04/May/2017:21:20:19 +0500] "GET /?url=producthunt.com&zoom=0.5&width=300&height=200 HTTP/1.1 200 9815" 4.763817 
127.0.0.1 - - [04/May/2017:21:20:19 +0500] "GET /?url=producthunt.com&zoom=0.5&width=300&height=200 HTTP/1.1 200 9815" 4.258401 
127.0.0.1 - - [04/May/2017:21:20:24 +0500] "GET /?url=producthunt.com&zoom=0.5&width=300&height=200 HTTP/1.1 200 9963" 4.909780 
127.0.0.1 - - [04/May/2017:21:20:30 +0500] "GET /?url=producthunt.com&zoom=0.5&width=300&height=200 HTTP/1.1 200 12457" 5.919063 
127.0.0.1 - - [04/May/2017:21:20:35 +0500] "GET /?url=producthunt.com HTTP/1.1 200 148446" 4.622700 
127.0.0.1 - - [04/May/2017:21:20:38 +0500] "GET /?url=producthunt.com&full=true HTTP/1.1 200 268263" 6.310466 
127.0.0.1 - - [04/May/2017:21:20:46 +0500] "GET /?url=producthunt.com&zoom=0.5 HTTP/1.1 200 106196" 4.824065 
127.0.0.1 - - [04/May/2017:21:20:53 +0500] "GET /?url=producthunt.com&zoom=0.5&width=300&height=200 HTTP/1.1 200 9963" 6.369481 
127.0.0.1 - - [04/May/2017:21:20:58 +0500] "GET /?url=producthunt.com&full=true HTTP/1.1 200 287242" 5.469234 
127.0.0.1 - - [04/May/2017:21:21:05 +0500] "GET /?url=producthunt.com&full=true HTTP/1.1 200 284747" 6.836958 
127.0.0.1 - - [04/May/2017:21:21:06 +0500] "GET /?url=producthunt.com&zoom=0.5 HTTP/1.1 200 105325" 7.179209 
127.0.0.1 - - [04/May/2017:21:21:11 +0500] "GET /?url=producthunt.com&full=true HTTP/1.1 200 286191" 5.403610 
127.0.0.1 - - [04/May/2017:21:21:15 +0500] "GET /?url=producthunt.com&full=true HTTP/1.1 200 251911" 3.905294 
127.0.0.1 - - [04/May/2017:21:21:20 +0500] "GET /?url=producthunt.com&zoom=0.5&width=300&height=200 HTTP/1.1 200 9815" 4.959146 
127.0.0.1 - - [04/May/2017:21:21:26 +0500] "GET /?url=producthunt.com&full=true HTTP/1.1 200 267899" 5.290420 
127.0.0.1 - - [04/May/2017:21:21:33 +0500] "GET /?url=producthunt.com&full=true HTTP/1.1 200 276484" 6.725540 
127.0.0.1 - - [04/May/2017:21:21:39 +0500] "GET /?url=producthunt.com&zoom=0.5 HTTP/1.1 200 106337" 6.556010 
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6026e45f0 pc=0x6026e45f0]

runtime stack:
runtime.throw(0x3ada23f, 0x2a)
	/home/milann/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
	/home/milann/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xa81150, 0xc420ae7f08, 0x76edae)
	/home/milann/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420ae7ed8 sp=0xc420ae7e98
github.com/therecipe/qt/widgets._Cfunc_QApplication_QApplication_Exec(0x0)
	github.com/therecipe/qt/widgets/_obj/_cgo_gotypes.go:871 +0x49 fp=0xc420ae7f08 sp=0xc420ae7ed8
github.com/therecipe/qt/widgets.QApplication_Exec(0xc42010a000)
	/home/milann/golang/src/github.com/therecipe/qt/widgets/widgets-minimal.go:723 +0x22 fp=0xc420ae7f20 sp=0xc420ae7f08
main.(*Loader).Exec(0xc4200117c0)
	/home/milann/golang/src/github.com/gen2brain/url2img/url2img/loader.go:176 +0x22 fp=0xc420ae7f38 sp=0xc420ae7f20
main.main()
	/home/milann/golang/src/github.com/gen2brain/url2img/url2img/main.go:36 +0x2e9 fp=0xc420ae7f88 sp=0xc420ae7f38
runtime.main()
	/home/milann/go/src/runtime/proc.go:185 +0x20a fp=0xc420ae7fe0 sp=0xc420ae7f88
runtime.goexit()
	/home/milann/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420ae7fe8 sp=0xc420ae7fe0

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/home/milann/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
	/home/milann/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/home/milann/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/home/milann/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [select, 1 minutes, locked to thread]:
runtime.gopark(0x3ae02c0, 0x0, 0x3acd662, 0x6, 0x18, 0x2)
	/home/milann/go/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc42003af50, 0x0, 0x18)
	/home/milann/go/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc42003af50)
	/home/milann/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/home/milann/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
	/home/milann/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 18 [chan receive, 1 minutes]:
main.(*Server).ListenAndServe.func3(0xc420020420, 0xc42005a070)
	/home/milann/golang/src/github.com/gen2brain/url2img/url2img/server.go:125 +0x40
created by main.(*Server).ListenAndServe
	/home/milann/golang/src/github.com/gen2brain/url2img/url2img/server.go:128 +0x147

goroutine 19 [IO wait]:
net.runtime_pollWait(0x7fa0cd6dff00, 0x72, 0x0)
	/home/milann/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4200fa0d8, 0x72, 0x0, 0xc42017f400)
	/home/milann/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4200fa0d8, 0xffffffffffffffff, 0x0)
	/home/milann/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4200fa070, 0x0, 0x6756060, 0xc42017f400)
	/home/milann/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc420106000, 0xc42003fed8, 0x9ca71e, 0x798c30)
	/home/milann/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).Accept(0xc420106000, 0x3adfd68, 0xc420b000a0, 0x675abe0, 0xc4201100c0)
	/home/milann/go/src/net/tcpsock.go:228 +0x49
net/http.(*Server).Serve(0xc420100000, 0x675a3e0, 0xc420106000, 0x0, 0x0)
	/home/milann/go/src/net/http/server.go:2643 +0x228
created by main.(*Server).ListenAndServe
	/home/milann/golang/src/github.com/gen2brain/url2img/url2img/server.go:154 +0x372

goroutine 28 [sleep]:
time.Sleep(0x989680)
	/home/milann/go/src/runtime/time.go:59 +0xf9
main.(*Server).wait(0xc42005a070, 0xc42011b240, 0x20, 0x0)
	/home/milann/golang/src/github.com/gen2brain/url2img/url2img/server.go:175 +0x199
main.(*Server).ServeHTTP(0xc42005a070, 0x675a360, 0xc42011b1c0, 0xc420070500)
	/home/milann/golang/src/github.com/gen2brain/url2img/url2img/server.go:71 +0x1b1
main.newHandler.func1(0x675a5e0, 0xc42012e1c0, 0xc420070500)
	/home/milann/golang/src/github.com/gen2brain/url2img/url2img/server.go:254 +0x4a5
net/http.HandlerFunc.ServeHTTP(0xc4200f8000, 0x675a5e0, 0xc42012e1c0, 0xc420070500)
	/home/milann/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0x677f660, 0x675a5e0, 0xc42012e1c0, 0xc420070500)
	/home/milann/go/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420100000, 0x675a5e0, 0xc42012e1c0, 0xc420070500)
	/home/milann/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420b000a0, 0x675ab20, 0xc4202cc100)
	/home/milann/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/home/milann/go/src/net/http/server.go:2668 +0x2ce

goroutine 34 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/home/milann/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 42 [IO wait]:
net.runtime_pollWait(0x7fa0cd6dfd80, 0x72, 0x7)
	/home/milann/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420170148, 0x72, 0x67577e0, 0x67536d8)
	/home/milann/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420170148, 0xc4202cc151, 0x1)
	/home/milann/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4201700e0, 0xc4202cc151, 0x1, 0x1, 0x0, 0x67577e0, 0x67536d8)
	/home/milann/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000e168, 0xc4202cc151, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/milann/go/src/net/net.go:181 +0x70
net/http.(*connReader).backgroundRead(0xc4202cc140)
	/home/milann/go/src/net/http/server.go:656 +0x58
created by net/http.(*connReader).startBackgroundRead
	/home/milann/go/src/net/http/server.go:652 +0xdf
```

**Comment by gen2brain** [comment]
Can be anything really, I guess related to WebKit, it is still technical preview so not even alpha. If you can reproduce it with same website better send this issue to WebKit project.

**Comment by gen2brain** [comment]
New version is released, with current build of QtWebKit. Some urls probably still crash, but it is still alpha.
